name: Ubuntu Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        if: matrix.os == 'ubuntu-18.04'
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      # Rest of the steps...
