name: Ubuntu Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
        python-version:
          - 3.6
          - 3.8
        include:
          - os: ubuntu-18.04
            python-version: 3.6
          - os: ubuntu-20.04
            python-version: 3.8
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Rest of the steps...
